#!/usr/bin/env python3
"""Render the paper's simulation snapshots: four phases of one real Gen3 throw.

Frames come from a real ``PyBulletThrowingSystem.rollout`` of the checkpoint the
paper reports -- ``results_kinetic_chain_gen3_tcp/1``, trained under
``kinova_gen3_dyn`` (computed-torque, so the release velocity is generated by
the simulated arm, not assigned) through the TCP-offset-corrected pose table.
This matters: renders of a ``kinematic``-mode profile show a cosmetic arm beside
a ball whose velocity was set directly, and must never be presented as a
physical throw. Nothing here is staged -- the policy picks the release speed and
the physics engine does the rest.

Differences from make_labeled_kinetic_chain_video.py, whose output was tried
first and is unusable in print: its camera frames the whole workspace, so the
arm occupies a small fraction of a column-width figure; its floor is PyBullet's
blue checkerboard, which at print size reads as the dominant object; and its
end-effector / ball / target callouts are debug overlays on tinted boxes.

Usage:  python3 make_throw_snapshots.py [--outdir ../overleaf/figs]
"""
from __future__ import annotations

import argparse
import os
import pathlib
import pickle as pkl
import sys

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
VARIANT = REPO / "mc-pilot-pybullet"

LOG_PATH = "results_kinetic_chain_gen3_tcp/1"
TABLE = "throw_pose_table_tcp.npy"
TOOL_OFFSET_Z = 0.12

SSAA = 3
PANEL_W, PANEL_H = 480, 700           # per phase, before the strip is assembled
INK = (26, 26, 26)

# Tight profile view of the swing plane, in ABSOLUTE world coordinates. The
# scene to keep in frame runs x = -0.3 (the arm reaching back at windup) to
# x = 0.9 (where the ball lands) and z = 0 to 1.75 (the release pose), so the
# view is centred on (0.35, 0.85) at a distance and field of view that just
# contains that box -- the first attempt reused the video renderer's preset,
# which is framed for the whole workspace and put the arm against the left
# edge with the ball outside the panel entirely.
# The camera is FITTED to the scene, not guessed. Two hand-picked framings were
# wrong in a row -- the first put the arm against the left edge, the second cut
# the windup pose off entirely, because the arm reaches back to x = -0.57 at
# windup, much further than it looks like it should. So pass 1 of the rollout
# records the ball and TCP positions with no rendering, and pass 2 renders with
# a view solved from the box those actually occupy.
CAM_DIST = 2.60
MARGIN = 0.08


def build(fit=None):
    """Run one rollout. With ``fit=None`` no frames are rendered and only the
    geometry needed to solve the camera is returned; pass that solution back in
    to render."""
    os.chdir(VARIANT)
    sys.path.insert(0, str(VARIANT))
    import pybullet as p
    import pybullet_data
    import torch
    from PIL import Image

    import policy_learning.Policy as Policy
    from robot_arm.robot_profiles import get_robot_profile
    from simulation_class.model_pybullet import PyBulletThrowingSystem
    from run_hardware_throw import _check_tool_offset_matches_table

    with open(os.path.join(LOG_PATH, "config_log.pkl"), "rb") as f:
        cfg = pkl.load(f)
    with open(os.path.join(LOG_PATH, "log.pkl"), "rb") as f:
        log = pkl.load(f)

    profile = get_robot_profile(cfg["robot_name"])
    if profile.control_mode != "torque":
        sys.exit(f"refusing to render {profile.name}: control_mode="
                 f"{profile.control_mode}, not a physical throw")

    st = log["parameters_trial_list"][-1]
    pol = Policy.Throwing_Policy(
        full_state_dim=8, target_dim=2, num_basis=st["centers"].shape[0],
        u_max=cfg["uM"],
        lengthscales_init=st["log_lengthscales"].exp().numpy()[0],
        centers_init=st["centers"].numpy(),
        weight_init=st["f_linear.weight"].numpy(),
        flg_drop=False, dtype=torch.float64, device=torch.device("cpu"))
    pol.load_state_dict(st)
    pol.eval()

    def policy(s, t):
        with torch.no_grad():
            inp = torch.tensor(np.asarray(s), dtype=torch.float64).unsqueeze(0)
            return np.array([float(pol(inp, t=0, p_dropout=0.0).item())])

    table = list(np.load(TABLE, allow_pickle=True))
    _check_tool_offset_matches_table(table, TOOL_OFFSET_Z)
    launch_deg = float(table[0]["elev_deg"])
    base_h = float(cfg.get("base_height", 0.0))

    rw, rh = PANEL_W * SSAA, PANEL_H * SSAA

    def cam(cid):
        cx, cz, fov = fit
        eye = [cx, -CAM_DIST, cz]
        tgt = [cx, 0.0, cz]
        view = p.computeViewMatrix(eye, tgt, [0, 0, 1], physicsClientId=cid)
        proj = p.computeProjectionMatrixFOV(fov, rw / rh, 0.05, 8.0,
                                            physicsClientId=cid)
        return view, proj

    sysm = PyBulletThrowingSystem(
        mass=cfg["ball_mass"], radius=cfg["ball_radius"],
        launch_angle_deg=launch_deg, arm_noise=None,
        t_w=cfg["T_W"], t_r=cfg["T_R"], robot_name=cfg["robot_name"],
        target_height=cfg["target_height"], opt_posture_table=table,
        opt_launch_deg=launch_deg, base_height=base_h,
        tool_offset=[0.0, 0.0, TOOL_OFFSET_Z])

    frames, ball_xyz, tcp_xyz = [], [], []
    styled = {"done": False}
    mats = {}

    def cap(cid):
        ball_xyz.append(np.array(
            p.getBasePositionAndOrientation(2, physicsClientId=cid)[0]))
        ls = p.getLinkState(1, profile.ee_link, computeForwardKinematics=True,
                            physicsClientId=cid)
        rot = np.array(p.getMatrixFromQuaternion(ls[5])).reshape(3, 3)
        tcp_xyz.append(np.array(ls[4]) + rot @ np.array([0.0, 0.0, TOOL_OFFSET_Z]))
        if fit is None:
            return
        if not styled["done"]:
            # Plain matte floor and a saturated ball. PyBullet's default plane
            # texture is a blue checkerboard that dominates a printed panel,
            # and the default ball is the same grey as the arm.
            p.changeVisualShape(0, -1, textureUniqueId=-1,
                                rgbaColor=[0.94, 0.94, 0.94, 1.0],
                                physicsClientId=cid)
            p.changeVisualShape(2, -1, rgbaColor=[0.0, 0.45, 0.70, 1.0],
                                physicsClientId=cid)
            # The mount plate is not part of the model -- base_height only
            # raises the arm's base frame -- so the arm renders floating with
            # an unexplained gap to the floor. Draw the plate the real Gen3
            # actually stands on. VISUAL ONLY: mass 0 and
            # baseCollisionShapeIndex=-1, so it cannot touch the ball or the
            # arm and the rollout is bit-identical with or without it. It is
            # also created after bodies 0/1/2, whose indices this file relies
            # on, so those are undisturbed.
            vs = p.createVisualShape(
                p.GEOM_BOX, halfExtents=[0.085, 0.085, base_h / 2.0],
                rgbaColor=[0.42, 0.45, 0.49, 1.0], physicsClientId=cid)
            p.createMultiBody(baseMass=0, baseCollisionShapeIndex=-1,
                              baseVisualShapeIndex=vs,
                              basePosition=[0.0, 0.0, base_h / 2.0],
                              physicsClientId=cid)
            styled["done"] = True
        view, proj = cam(cid)
        mats.setdefault("view", view)      # camera is static; capture once
        mats.setdefault("proj", proj)
        img = p.getCameraImage(rw, rh, viewMatrix=view, projectionMatrix=proj,
                               renderer=p.ER_TINY_RENDERER, physicsClientId=cid)
        rgb = np.reshape(img[2], (rh, rw, 4))[:, :, :3].astype(np.uint8)
        frames.append(np.asarray(
            Image.fromarray(rgb).resize((PANEL_W, PANEL_H), Image.LANCZOS)))

    sysm.frame_hook = cap
    release_pos = np.array(cfg["release_pos"], dtype=float)
    target = np.array([0.78, 0.0])
    s0 = np.concatenate([release_pos, np.zeros(3), target])
    pos, _, _ = sysm.rollout(s0, policy, T=cfg["T"], dt=cfg["Ts"], noise=0.0)

    land = pos[-1][:2]
    err = float(np.linalg.norm(land - target))
    v_rel = sysm.last_release_info["v_release"]
    print(f"  target ({target[0]:.3f}, {target[1]:.3f})  landed "
          f"({land[0]:.3f}, {land[1]:.3f})  err {err*100:.2f} cm  "
          f"|v_release| {np.linalg.norm(v_rel):.3f} m/s  frames {len(frames)}")

    # Phase indices read off the frame stream, not from assumed timing: the
    # torque controller may stretch the throw ramp, so t_r is not necessarily
    # cfg["T_R"]. Release is the first frame at which the ball has actually
    # separated from the gripper -- measured as its distance from the TCP
    # exceeding one ball radius. Keying release off the ball's own forward
    # velocity instead (the first attempt) fires mid-swing, while the ball is
    # still held and merely being carried forward by the arm, which put a
    # still-gripped ball in the panel labelled "flight".
    ball = np.asarray(ball_xyz)
    tcp = np.asarray(tcp_xyz)
    dt_frames = len(ball_xyz)   # frames is empty on the geometry-only pass
    sep = np.linalg.norm(ball - tcp, axis=1)
    held = sep < (cfg["ball_radius"] + 0.01)
    i_release = int(np.argmax(~held & (np.arange(dt_frames) > 5)))
    i_windup = int(np.argmin(ball[: max(i_release, 1), 0]))
    i_land = int(np.argmin(ball[:, 2]))
    i_flight = (i_release + i_land) // 2
    idx = [i_windup, i_release, i_flight, i_land]
    print(f"  phase frames: windup {i_windup}, release {i_release}, "
          f"flight {i_flight}, landing {i_land}  (of {dt_frames})")
    if fit is None:
        sel = np.array([ball[i] for i in idx] + [tcp[i] for i in idx])
        x0, x1 = sel[:, 0].min(), sel[:, 0].max()
        z0, z1 = sel[:, 2].min(), sel[:, 2].max()
        mx, mz = MARGIN * (x1 - x0), MARGIN * (z1 - z0)
        x0, x1, z0, z1 = x0 - mx, x1 + mx, z0 - mz, z1 + mz
        print(f"  content x [{x0:.3f}, {x1:.3f}]  z [{z0:.3f}, {z1:.3f}]")
        # Solve the vertical field of view for the taller of the two demands,
        # so neither axis is cropped whatever the panel aspect happens to be.
        half_z = max((z1 - z0) / 2.0, (x1 - x0) / 2.0 * PANEL_H / PANEL_W)
        fov = 2.0 * np.degrees(np.arctan(half_z / CAM_DIST))
        return ((x0 + x1) / 2.0, (z0 + z1) / 2.0, fov)
    ann = dict(
        view=mats["view"], proj=mats["proj"],
        ball=[ball[i] for i in idx],
        arc=ball[i_release:i_land + 1],
        v_release=np.asarray(v_rel, dtype=float),
        target=np.array([target[0], target[1], 0.0]),
        base_h=base_h, err=err,
    )
    return [frames[i] for i in idx], ann


def _project(view, proj, xyz, w, h):
    """World point -> pixel in a w x h panel.

    PyBullet returns both matrices as column-major 16-tuples, hence the
    transposes. Points behind the camera come back as None rather than being
    mirrored to a bogus in-frame pixel.
    """
    v = np.asarray(view, dtype=float).reshape(4, 4).T
    pr = np.asarray(proj, dtype=float).reshape(4, 4).T
    clip = pr @ (v @ np.array([xyz[0], xyz[1], xyz[2], 1.0]))
    if clip[3] <= 1e-9:
        return None
    ndc = clip[:3] / clip[3]
    return ((ndc[0] * 0.5 + 0.5) * w, (1.0 - (ndc[1] * 0.5 + 0.5)) * h)


def _dashed(d, pts, fill, width, dash=13, gap=9):
    """Dashed polyline. PIL has no dash support, so walk the path by arclength."""
    carry, draw_on = 0.0, True
    for (x0, y0), (x1, y1) in zip(pts[:-1], pts[1:]):
        seg = float(np.hypot(x1 - x0, y1 - y0))
        t = 0.0
        while t < seg:
            step = min((dash if draw_on else gap) - carry, seg - t)
            if draw_on:
                a = (x0 + (x1 - x0) * t / seg, y0 + (y1 - y0) * t / seg)
                b = (x0 + (x1 - x0) * (t + step) / seg,
                     y0 + (y1 - y0) * (t + step) / seg)
                d.line([a, b], fill=fill, width=width)
            t += step
            carry += step
            if carry >= (dash if draw_on else gap):
                carry, draw_on = 0.0, not draw_on


def _arrowhead(d, tip, direction, fill, size=13):
    ux, uy = direction / (np.linalg.norm(direction) + 1e-12)
    px, py = -uy, ux
    d.polygon([tuple(tip),
               (tip[0] - ux * size + px * size * 0.45,
                tip[1] - uy * size + py * size * 0.45),
               (tip[0] - ux * size - px * size * 0.45,
                tip[1] - uy * size - py * size * 0.45)], fill=fill)


def _callout(d, font, text, anchor, offset, ink, panel, pad=4):
    """Black text on a white pad, joined to its anchor by a thin leader.

    The label is kept inside the panel: if the requested offset would push it
    past an edge, the horizontal offset is mirrored and the result clamped.
    Without this, three of the four callouts printed off the panel and lost
    their first or last characters.
    """
    pw, ph = panel
    w = d.textlength(text, font=font)
    h = font.size
    tx, ty = anchor[0] + offset[0], anchor[1] + offset[1]
    if tx - pad < 0 or tx + w + pad > pw:
        tx = anchor[0] - offset[0] - (w if offset[0] > 0 else 0)
    tx = min(max(tx, pad + 1), pw - w - pad - 1)
    ty = min(max(ty, pad + 1), ph - h - pad - 1)
    # leader meets whichever side of the label faces the anchor
    join = (tx + w, ty + h / 2) if tx + w / 2 < anchor[0] else (tx, ty + h / 2)
    d.line([anchor, join], fill=(120, 120, 120), width=2)
    d.rectangle([tx - pad, ty - pad, tx + w + pad, ty + h + pad], fill="white")
    d.text((tx, ty), text, fill=ink, font=font)


def compose(panels, ann, outdir):
    from PIL import Image, ImageDraw, ImageFont

    titles = ["(a) windup", "(b) release", "(c) flight", "(d) landing"]
    serif = "/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf"
    fallback = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    fp = serif if os.path.exists(serif) else fallback
    font = ImageFont.truetype(fp, 30)
    small = ImageFont.truetype(fp, 23)

    h, w = panels[0].shape[0], panels[0].shape[1]
    view, proj = ann["view"], ann["proj"]

    def P(xyz):
        return _project(view, proj, xyz, w, h)

    BLUE = (0, 90, 160)
    annotated = []
    for i, arr in enumerate(panels):
        im = Image.fromarray(arr).copy()
        d = ImageDraw.Draw(im)
        ball = P(ann["ball"][i])

        if i == 0:
            # The arm stands on a 0.433 m plate, which the render cannot show
            # (the plate is not modelled -- only the raised base is), so the
            # gap between floor and first joint is otherwise unexplained.
            top, bot = P([0.0, 0.0, ann["base_h"]]), P([0.0, 0.0, 0.0])
            # Dimension to the RIGHT of the base: the left side is where the
            # arm reaches at windup, and the label ran off the panel there.
            xline = top[0] + 0.24 * w
            d.line([(xline, top[1]), (xline, bot[1])], fill=(90, 90, 90), width=2)
            for yy in (top[1], bot[1]):
                d.line([(xline - 7, yy), (xline + 7, yy)], fill=(90, 90, 90), width=2)
            _callout(d, small, f"mount plate {ann['base_h']:.3f} m",
                     (xline, (top[1] + bot[1]) / 2), (24, -12), INK, (w, h))
            _callout(d, small, "object", ball, (30, -60), INK, (w, h))

        elif i == 1:
            v = ann["v_release"]
            tipw = ann["ball"][i] + v / (np.linalg.norm(v) + 1e-12) * 0.42
            tip = P(tipw)
            d.line([ball, tip], fill=BLUE, width=4)
            _arrowhead(d, np.array(tip), np.array(tip) - np.array(ball), BLUE)
            _callout(d, small, f"release {np.linalg.norm(v):.2f} m/s", tip,
                     (18, -40), INK, (w, h))

        elif i == 2:
            pts = [P(q) for q in ann["arc"][::3]]
            pts = [q for q in pts if q is not None]
            _dashed(d, pts, BLUE, 3)
            # anchored low on the arc, where there is clear space to its left
            _callout(d, small, "ballistic flight", pts[int(len(pts) * 0.85)],
                     (-250, 14), INK, (w, h))

        else:
            tgt = P(ann["target"])
            d.line([(tgt[0], tgt[1] - 22), (tgt[0], tgt[1] + 22)],
                   fill=(90, 90, 90), width=3)
            _callout(d, small, "target", (tgt[0], tgt[1] - 22), (-170, -60), INK,
                     (w, h))
            # Direction-neutral wording on purpose: this throw overshoots
            # (0.816 m against a 0.780 m target), and "short" would be wrong.
            _callout(d, small, f"landed {ann['err'] * 100:.1f} cm from target",
                     ball, (-330, 30), INK, (w, h))

        annotated.append(im)

    # One row of four, placed as a figure* across \textwidth. At \linewidth in
    # a 3.11in column a 2x2 grid gives 1.5in panels and stands 4.6in tall --
    # half a column for one figure; the full-width strip gives larger panels
    # in less vertical space.
    gap, cap_h, rule = 12, 46, 2
    sheet = Image.new("RGB", (w * 4 + gap * 3, h + cap_h), "white")
    d = ImageDraw.Draw(sheet)
    for i, (im, t) in enumerate(zip(annotated, titles)):
        x = i * (w + gap)
        sheet.paste(im, (x, 0))
        d.rectangle([x, 0, x + w - 1, h - 1], outline=(190, 190, 190), width=rule)
        tw = d.textlength(t, font=font)
        d.text((x + (w - tw) / 2, h + 7), t, fill=INK, font=font)

    outdir = pathlib.Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    sheet.save(outdir / "fig_throw_snapshots.png")
    print(f"  wrote fig_throw_snapshots.png  {sheet.size}")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--outdir", default=str(HERE.parent / "overleaf" / "figs"))
    args = ap.parse_args()
    outdir = pathlib.Path(args.outdir).resolve()
    fit = build()                      # pass 1: geometry only, solves the camera
    print(f"  camera: centre ({fit[0]:.3f}, {fit[1]:.3f})  fov {fit[2]:.1f} deg")
    panels, ann = build(fit)           # pass 2: render
    compose(panels, ann, outdir)


if __name__ == "__main__":
    main()
